# SPDX-License-Identifier: MIT
"""FS1B: per-pair frame-transform selector side-info (Phase 1b, Fable campaign).

Wire format — appended at the very END of the archive member `x`, self-delimiting
so any base payload member can carry it:

  [u32-word range-coded index stream] [u8 K] [u8 base_kind] [u16 n_words] [b"FS1B"]

Parsed from the end. base_kind: 1 = rhnerv_comma-style member precedes (ctx
container + FEC6 selector + trailing 607-B #101 sidecar); 0 = fable_ft-style
member precedes (ctx container, empty selector, no sidecar).

Indices are coded with an adaptive K-ary range coder (constriction), counts
prior 0.5, pair order 0..599. Index 0 = "none". The mode PALETTE (index ->
transform) is decoder-known code in fs1b_palette.py (generated by compress.py;
not transmitted — same convention as PR #110's FEC6 Huffman codebook).

Modes are deterministic integer transforms applied AFTER the base payload's
full pixel chain (bias + clamp/round + FEC6 if present), followed by one final
clamp/round — identical semantics to the FEC6 apply, but allowed to target
frame1 (which SegNet scores) as well as frame0.
"""
from __future__ import annotations

import struct

import numpy as np
import torch

MAGIC = b"FS1B"
N_PAIRS = 600


# ------------------------------------------------------------------ coding ---
def _probs(counts):
    return counts / counts.sum()


LATENT_DIM = 28
# delta grid in latent-space x100 (PR #101 sidecar grid, absolute units)
SIDECAR_DELTAS_X100 = (-10, -8, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 8, 10)
_FLAG_SIDECAR = 0x80
_FLAG_NO_MODES = 0x40


MAX_CORR_PER_PAIR = 2


def _encode_sidecar(corrections):
    """corrections: list of (pair, dim, delta_x100), delta on the grid, at most
    MAX_CORR_PER_PAIR per pair (distinct dims). Returns u32-word coded bytes.
    Per pair: count symbol c in {0,1,2} (adaptive ternary), then c x (dim, delta),
    entries sorted by dim for a canonical stream."""
    import constriction
    per_pair = {}
    for pair, dim, dx in corrections:
        assert 0 <= pair < N_PAIRS and 0 <= dim < LATENT_DIM
        assert int(dx) in SIDECAR_DELTAS_X100
        per_pair.setdefault(int(pair), []).append((int(dim), SIDECAR_DELTAS_X100.index(int(dx))))
    for pair, lst in per_pair.items():
        assert len(lst) <= MAX_CORR_PER_PAIR
        assert len({d for d, _ in lst}) == len(lst), "duplicate dim in one pair"
        lst.sort()
    enc = constriction.stream.queue.RangeEncoder()
    cnt_c = np.full(MAX_CORR_PER_PAIR + 1, 0.5)
    dim_c = np.full(LATENT_DIM, 0.5)
    del_c = np.full(len(SIDECAR_DELTAS_X100), 0.5)
    for pair in range(N_PAIRS):
        lst = per_pair.get(pair, [])
        c = len(lst)
        enc.encode(c, constriction.stream.model.Categorical(_probs(cnt_c), perfect=False))
        cnt_c[c] += 1
        for d, k in lst:
            enc.encode(d, constriction.stream.model.Categorical(_probs(dim_c), perfect=False))
            dim_c[d] += 1
            enc.encode(k, constriction.stream.model.Categorical(_probs(del_c), perfect=False))
            del_c[k] += 1
    return enc.get_compressed().tobytes()


def _decode_sidecar(block_bytes):
    import constriction
    words = np.frombuffer(block_bytes, dtype=np.uint32).copy()
    dec = constriction.stream.queue.RangeDecoder(words)
    cnt_c = np.full(MAX_CORR_PER_PAIR + 1, 0.5)
    dim_c = np.full(LATENT_DIM, 0.5)
    del_c = np.full(len(SIDECAR_DELTAS_X100), 0.5)
    out = []
    for pair in range(N_PAIRS):
        c = int(dec.decode(constriction.stream.model.Categorical(_probs(cnt_c), perfect=False)))
        cnt_c[c] += 1
        for _ in range(c):
            d = int(dec.decode(constriction.stream.model.Categorical(_probs(dim_c), perfect=False)))
            dim_c[d] += 1
            k = int(dec.decode(constriction.stream.model.Categorical(_probs(del_c), perfect=False)))
            del_c[k] += 1
            out.append((pair, d, SIDECAR_DELTAS_X100[k]))
    return out


def apply_latent_corrections(latents, corrections):
    """latents (600,28) fp32 tensor; corrections [(pair,dim,delta_x100)]."""
    if not corrections:
        return latents
    latents = latents.clone()
    for pair, dim, dx in corrections:
        latents[int(pair), int(dim)] += np.float32(int(dx)) / np.float32(100.0)
    return latents


def encode_tail(indices, K, base_kind, corrections=()):
    """Full FS1B tail:
    [sc words][u16 sc_nwords]? [idx words][u8 K][u8 flags][u16 idx_nwords][MAGIC]
    flags = base_kind | 0x80 if sidecar present."""
    import constriction
    assert len(indices) == N_PAIRS and all(0 <= i < K for i in indices)
    flags = int(base_kind)
    if any(i != 0 for i in indices):
        assert K >= 2
        enc = constriction.stream.queue.RangeEncoder()
        counts = np.full(K, 0.5, dtype=np.float64)
        for sym in indices:
            model = constriction.stream.model.Categorical(_probs(counts), perfect=False)
            enc.encode(int(sym), model)
            counts[int(sym)] += 1.0
        idx_words = enc.get_compressed()
        idx_blob = idx_words.tobytes()
        n_words = len(idx_words)
    else:
        flags |= _FLAG_NO_MODES
        idx_blob, n_words, K = b"", 0, 1
    head = b""
    if corrections:
        flags |= _FLAG_SIDECAR
        sc = _encode_sidecar(corrections)
        assert len(sc) % 4 == 0
        head = sc + struct.pack("<H", len(sc) // 4)
    return (head + idx_blob
            + struct.pack("<BBH", K, flags, n_words) + MAGIC)


def decode_tail(member_bytes):
    """Returns (indices, base_kind, corrections, tail_len).
    No FS1B tail: ([0]*600, None, [], 0)."""
    import constriction
    if member_bytes[-4:] != MAGIC:
        return [0] * N_PAIRS, None, [], 0
    K, flags, n_words = struct.unpack("<BBH", member_bytes[-8:-4])
    base_kind = flags & 0x03
    idx_len = 8 + 4 * n_words
    if flags & _FLAG_NO_MODES:
        out = [0] * N_PAIRS
    else:
        words = np.frombuffer(member_bytes[-idx_len:-8], dtype=np.uint32).copy()
        dec = constriction.stream.queue.RangeDecoder(words)
        counts = np.full(K, 0.5, dtype=np.float64)
        out = []
        for _ in range(N_PAIRS):
            model = constriction.stream.model.Categorical(_probs(counts), perfect=False)
            sym = int(dec.decode(model))
            out.append(sym)
            counts[sym] += 1.0
    tail_len = idx_len
    corrections = []
    if flags & _FLAG_SIDECAR:
        sc_nwords = struct.unpack("<H", member_bytes[-(idx_len + 2):-idx_len])[0]
        sc_len = 4 * sc_nwords
        block = member_bytes[-(idx_len + 2 + sc_len):-(idx_len + 2)]
        corrections = _decode_sidecar(block)
        tail_len = idx_len + 2 + sc_len
    return out, base_kind, corrections, tail_len


# backward-compat wrappers (v1 tails decode fine via decode_tail)
def encode_indices(indices, K, base_kind):
    return encode_tail(indices, K, base_kind, ())


def decode_indices(member_bytes):
    idx, base_kind, _corr, tail_len = decode_tail(member_bytes)
    return idx, base_kind, tail_len


# ----------------------------------------------------------------- applying --
_BLUE_8 = torch.tensor([
    [-1, 1, -1, 1, 1, -1, 1, -1],
    [1, -1, 1, -1, -1, 1, -1, 1],
    [-1, 1, 1, -1, 1, -1, -1, 1],
    [1, -1, -1, 1, -1, 1, 1, -1],
    [1, 1, -1, -1, 1, 1, -1, -1],
    [-1, -1, 1, 1, -1, -1, 1, 1],
    [1, -1, -1, 1, 1, -1, -1, 1],
    [-1, 1, 1, -1, -1, 1, 1, -1],
], dtype=torch.float32)


def _blue_tile(h, w, device, dtype):
    tile = _BLUE_8.to(device=device, dtype=dtype)
    return tile.repeat((h + 7) // 8, (w + 7) // 8)[:h, :w]


def apply_mode(frame_chw: torch.Tensor, family: str, params) -> torch.Tensor:
    if family == "none":
        return frame_chw
    out = frame_chw.clone()
    if family == "rgb_bias":
        return out + torch.tensor(params, dtype=out.dtype, device=out.device).view(3, 1, 1)
    if family == "blue_chroma":
        amp = float(params[0])
        _c, h, w = out.shape
        tile = _blue_tile(h, w, out.device, out.dtype)
        out[0].add_(tile * amp)
        out[2].sub_(tile * amp)
        return out
    if family == "roll":
        dx, dy = int(params[0]), int(params[1])
        return torch.roll(out, shifts=(dy, dx), dims=(1, 2))
    raise ValueError(f"unknown FS1B family {family!r}")


def apply_selector_to_frames(frames_bchw: torch.Tensor, indices, palette,
                             *, pair_start: int) -> torch.Tensor:
    """Apply FS1B per-pair modes to a flat (2*n_pairs,3,H,W) rounded batch,
    then one final clamp/round (FEC6-identical semantics)."""
    if frames_bchw.shape[0] % 2 != 0:
        raise ValueError("FS1B expects complete frame pairs")
    out = frames_bchw.clone()
    n_pairs = frames_bchw.shape[0] // 2
    for off in range(n_pairs):
        idx = int(indices[pair_start + off])
        if idx == 0:
            continue
        fidx, family, params = palette[idx]
        fo = off * 2 + int(fidx)
        out[fo] = apply_mode(out[fo], family, params)
    return out.clamp_(0.0, 255.0).round_()
