#!/usr/bin/env python
# SPDX-License-Identifier: MIT
"""Inflate a base payload archive carrying an optional FS1B selector tail.

Member `x` = [base member bytes] ++ [FS1B tail (optional)].
base_kind (from the FS1B tail; defaults to 1 when absent):
  1: rhnerv_comma (#112) member — ctx container + FEC6 selector + 607-B sidecar
  0: fable_ft (Phase-2) member — ctx container, empty selector section

Pixel chain: base decode (HNeRV -> bicubic 874x1164 -> #98 biases ->
clamp/round -> [FEC6 if base 1]) then FS1B per-pair modes, final clamp/round,
uint8 NHWC streamed write. CPU-pinned, deterministic.

Deps: numpy, torch, constriction (harness base env).
"""
from __future__ import annotations

import sys
from pathlib import Path

import torch
import torch.nn.functional as F

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import fs1b  # noqa: E402
from fs1b_palette import PALETTE  # noqa: E402  (generated by compress.py)
import codec_ctx  # noqa: E402
from codec import (  # noqa: E402
    BASE_CHANNELS, EVAL_SIZE, LATENT_DIM, N_PAIRS,
    decode_decoder_compact, decode_latents_compact,
)
from codec_sidecar import SIDECAR_HUFF_ENUM_LEN, apply_latent_sidecar  # noqa: E402
from model import HNeRVDecoder  # noqa: E402
import base_inflate_rhnerv as rh  # noqa: E402  (FEC6 unpack/apply, verbatim #112)

CAMERA_H, CAMERA_W = 874, 1164


def parse_member(member_bytes: bytes):
    indices, base_kind, corrections, tail_len = fs1b.decode_tail(member_bytes)
    base = member_bytes[:-tail_len] if tail_len else member_bytes
    if base_kind is None:
        base_kind = 1
    if base_kind == 1:
        sidecar = base[-SIDECAR_HUFF_ENUM_LEN:]
        container = base[:-SIDECAR_HUFF_ENUM_LEN]
        streams, latent_raw, selector_payload = codec_ctx.unpack_container(container)
        decoder_sd = decode_decoder_compact(b"".join(streams))
        latents = apply_latent_sidecar(decode_latents_compact(latent_raw), sidecar)
        fec6 = rh.unpack_fec6_selector(selector_payload)
    elif base_kind == 0:
        streams, latent_raw, _sel = codec_ctx.unpack_container(base)
        decoder_sd = decode_decoder_compact(b"".join(streams))
        latents = decode_latents_compact(latent_raw)
        fec6 = None
    else:
        raise ValueError(f"unknown FS1B base_kind {base_kind}")
    # FS1B latent-correction sidecar: applied to fp32 latents BEFORE decode
    latents = fs1b.apply_latent_corrections(latents, corrections)
    return decoder_sd, latents, fec6, indices


def inflate(src_bin: str, dst_raw: str) -> int:
    decoder_sd, latents, fec6, indices = parse_member(Path(src_bin).read_bytes())
    device = torch.device("cpu")
    decoder = HNeRVDecoder(latent_dim=LATENT_DIM, base_channels=BASE_CHANNELS,
                           eval_size=EVAL_SIZE).to(device)
    decoder.load_state_dict(decoder_sd)
    decoder.eval()
    latents = latents.to(device)
    eval_h, eval_w = EVAL_SIZE
    n = 0
    with torch.inference_mode(), open(dst_raw, "wb") as fout:
        for i in range(0, N_PAIRS, 16):
            j = min(i + 16, N_PAIRS)
            b = j - i
            decoded = decoder(latents[i:j])
            flat = decoded.reshape(b * 2, 3, eval_h, eval_w)
            up = F.interpolate(flat, size=(CAMERA_H, CAMERA_W), mode="bicubic",
                               align_corners=False)
            up = up.reshape(b, 2, 3, CAMERA_H, CAMERA_W)
            up[:, 0, 0].sub_(1.0)
            up[:, 0, 2].sub_(1.0)
            up[:, 1, 1].sub_(1.0)
            rounded = up.reshape(b * 2, 3, CAMERA_H, CAMERA_W).clamp(0, 255).round()
            if fec6 is not None:
                codes, specs = fec6
                rounded = rh.apply_compact_selector_to_frames(
                    rounded, codes, specs, pair_start=i)
            rounded = fs1b.apply_selector_to_frames(
                rounded, indices, PALETTE, pair_start=i)
            fout.write(rounded.to(torch.uint8).permute(0, 2, 3, 1).cpu().numpy().tobytes())
            n += b * 2
    print(f"saved {n} frames")
    return n


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("Usage: python inflate.py <src.bin> <dst.raw>")
    inflate(sys.argv[1], sys.argv[2])
