#!/usr/bin/env python
# SPDX-License-Identifier: MIT
"""Build a composed archive: base payload archive + FS1B selector tail.

Reads a selection JSON (from work/phase1b robust gates) of the form
  {"selections": [{"pair": int, "mode": [frame_idx, family, [params...]]}, ...]}
derives the palette (index 0 = none), regenerates fs1b_palette.py, entropy-codes
the 600 indices, appends the tail to the base member, re-zips (STORED), and
round-trip asserts (decode -> identical indices + palette semantics).

Usage:
  python compress.py <base_archive.zip> <selection.json> <out_archive.zip> \
      --base-kind {0,1}
base_kind 1 = rhnerv_comma (#112) base; 0 = compact ctx-container base.
An EMPTY selection list yields a byte-identical passthrough of the base archive
(no tail appended).
"""
from __future__ import annotations

import argparse
import io
import json
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
import sys
sys.path.insert(0, str(HERE))
import fs1b  # noqa: E402


def build_palette(selections):
    """Stable palette: index 0 = none, then unique modes in first-use order."""
    palette = [(0, "none", ())]
    seen = {}
    indices = [0] * fs1b.N_PAIRS
    for s in selections:
        fidx, family, params = s["mode"][0], s["mode"][1], tuple(s["mode"][2])
        key = (int(fidx), str(family), params)
        if key not in seen:
            seen[key] = len(palette)
            palette.append(key)
        indices[int(s["pair"])] = seen[key]
    return palette, indices


def write_palette_module(palette, path):
    lines = ["# GENERATED by compress.py — decoder-known FS1B palette (not transmitted)",
             "PALETTE = ["]
    for fidx, family, params in palette:
        lines.append(f"    ({fidx!r}, {family!r}, {tuple(params)!r}),")
    lines.append("]\n")
    path.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("base_archive")
    ap.add_argument("selection_json")
    ap.add_argument("out_archive")
    ap.add_argument("--base-kind", type=int, required=True, choices=(0, 1))
    args = ap.parse_args()

    member = zipfile.ZipFile(args.base_archive).read("x")
    sel = json.loads(Path(args.selection_json).read_text())
    selections = sel["selections"]
    corrections = [tuple(c) for c in sel.get("latent_corrections", [])]

    if not selections and not corrections:
        Path(args.out_archive).write_bytes(Path(args.base_archive).read_bytes())
        print("empty selection -> passthrough copy of base archive")
        return

    palette, indices = build_palette(selections)
    if len(palette) > 255:
        raise SystemExit("palette too large for u8 K")
    write_palette_module(palette, HERE / "fs1b_palette.py")

    tail = fs1b.encode_tail(indices, max(len(palette), 1), args.base_kind, corrections)
    composed = member + tail

    # round-trip assert
    dec_idx, dec_kind, dec_corr, tail_len = fs1b.decode_tail(composed)
    assert (dec_idx == indices and dec_kind == args.base_kind
            and sorted(dec_corr) == sorted(corrections) and tail_len == len(tail)), \
        "FS1B round-trip failed"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_STORED) as zf:
        zi = zipfile.ZipInfo("x", date_time=(1980, 1, 1, 0, 0, 0))
        zf.writestr(zi, composed)
    Path(args.out_archive).write_bytes(buf.getvalue())
    n_mod = sum(1 for i in indices if i != 0)
    print(f"wrote {args.out_archive}: base {len(member):,} B + FS1B tail {len(tail)} B "
          f"({n_mod} frame modes, {len(corrections)} latent corrections, "
          f"K={len(palette)}) -> archive {len(buf.getvalue()):,} B")


if __name__ == "__main__":
    main()
