# GENERATED by compress.py — decoder-known FS1B palette (not transmitted)
PALETTE = [
    (0, 'none', ()),
    (0, 'rgb_bias', (0, -1, 1)),
    (0, 'rgb_bias', (-4, -4, -4)),
    (0, 'rgb_bias', (2, -1, -1)),
    (0, 'rgb_bias', (4, -2, -2)),
    (0, 'rgb_bias', (0, -2, 2)),
    (0, 'rgb_bias', (-2, -2, -2)),
    (0, 'roll', (0, 1)),
    (0, 'rgb_bias', (-1, -1, -1)),
    (0, 'blue_chroma', (3,)),
]
