#!/usr/bin/env python
# SPDX-License-Identifier: MIT
"""Inflate the qlp_exactgrid archive.

Member `x` = [compact PR #112 ctx-container base] ++ [FS1B pose-selector tail].
The base carries the frozen PR #101 HNeRV decoder + the exact-grid-polished
per-pair latents (no FEC6 selector, no sidecar). The FS1B tail carries the
re-searched per-pair frame0 pose modes.

Reuses the merged PR #112 modules from `submissions/rhnerv_comma/` (codec_ctx,
codec, model) rather than vendoring copies; only the FS1B tail code (`fs1b.py`,
`fs1b_palette.py`) is specific to this submission.

Pixel chain: HNeRV decode -> bicubic 874x1164 -> #98 channel biases ->
clamp/round -> FS1B per-pair frame0 modes -> final clamp/round -> uint8 NHWC
streamed write. CPU-pinned, deterministic. Deps: numpy, torch, constriction.
"""
from __future__ import annotations

import sys
from pathlib import Path

import torch
import torch.nn.functional as F

HERE = Path(__file__).resolve().parent
RHNERV = HERE.parent / "rhnerv_comma"   # merged PR #112 — reused, not vendored
sys.path.insert(0, str(RHNERV))
sys.path.insert(0, str(HERE))

import fs1b  # noqa: E402
from fs1b_palette import PALETTE  # noqa: E402  (generated by fs1b_compress.py)
import codec_ctx  # noqa: E402  (merged PR #112)
from codec import (  # noqa: E402  (merged PR #112)
    BASE_CHANNELS, EVAL_SIZE, LATENT_DIM, N_PAIRS,
    decode_decoder_compact, decode_latents_compact,
)
from model import HNeRVDecoder  # noqa: E402  (merged PR #95, carried by #112)

CAMERA_H, CAMERA_W = 874, 1164


def parse_member(member_bytes: bytes):
    indices, base_kind, corrections, tail_len = fs1b.decode_tail(member_bytes)
    base = member_bytes[:-tail_len] if tail_len else member_bytes
    if base_kind not in (0, None):
        raise ValueError(f"qlp_exactgrid ships FS1B base_kind 0; got {base_kind}")
    streams, latent_raw, _selector = codec_ctx.unpack_container(base)
    decoder_sd = decode_decoder_compact(b"".join(streams))
    latents = decode_latents_compact(latent_raw)
    # FS1B latent-correction sidecar (empty for this submission): fp32, pre-decode
    latents = fs1b.apply_latent_corrections(latents, corrections)
    return decoder_sd, latents, indices


def inflate(src_bin: str, dst_raw: str) -> int:
    decoder_sd, latents, indices = parse_member(Path(src_bin).read_bytes())
    device = torch.device("cpu")
    decoder = HNeRVDecoder(latent_dim=LATENT_DIM, base_channels=BASE_CHANNELS,
                           eval_size=EVAL_SIZE).to(device)
    decoder.load_state_dict(decoder_sd)
    decoder.eval()
    latents = latents.to(device)
    eval_h, eval_w = EVAL_SIZE
    n = 0
    with torch.inference_mode(), open(dst_raw, "wb") as fout:
        for i in range(0, N_PAIRS, 16):
            j = min(i + 16, N_PAIRS)
            b = j - i
            decoded = decoder(latents[i:j])
            flat = decoded.reshape(b * 2, 3, eval_h, eval_w)
            up = F.interpolate(flat, size=(CAMERA_H, CAMERA_W), mode="bicubic",
                               align_corners=False)
            up = up.reshape(b, 2, 3, CAMERA_H, CAMERA_W)
            up[:, 0, 0].sub_(1.0)
            up[:, 0, 2].sub_(1.0)
            up[:, 1, 1].sub_(1.0)
            rounded = up.reshape(b * 2, 3, CAMERA_H, CAMERA_W).clamp(0, 255).round()
            rounded = fs1b.apply_selector_to_frames(
                rounded, indices, PALETTE, pair_start=i)
            fout.write(rounded.to(torch.uint8).permute(0, 2, 3, 1).cpu().numpy().tobytes())
            n += b * 2
    print(f"saved {n} frames")
    return n


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("Usage: python inflate.py <src.bin> <dst.raw>")
    inflate(sys.argv[1], sys.argv[2])
